#!/bin/sh
#
# File:        run
# Author:      Kyle Mulleady
# Description: Use this file to execute the Graph app from the command line.
# Usage:       ./run <vna_file> [<vna_file> ...]

echo "Compiling and running Kyle Mulleady's Graph project..."

cd src && \
javac -d ../bin/ ics311km2/*.java && \
cd ../bin/ && \
java ics311km2/Driver $* && \
cd ..

echo "Done."
